services:
  - docker

env:
  global:
    - DOCKER_ACCOUNT=sogis
    - DOCKER_REPO=docker-mapcache

script:
  - docker pull $DOCKER_ACCOUNT/$DOCKER_REPO:latest
  - docker build -t $DOCKER_ACCOUNT/$DOCKER_REPO:latest -t $DOCKER_ACCOUNT/$DOCKER_REPO:$TRAVIS_BUILD_NUMBER .
  - docker run -d --rm -e ENVIRONMENT='' -p 8080:8080 sogis/docker-mapcache:latest
  - curl -f http://localhost:8080/mapcache/wmts/1.0.0/WMTSCapabilities.xml
  - curl -f --output /tmp/tile.png http://localhost:8080/mapcache/wmts/1.0.0/ch.so.agi.hintergrundkarte_sw/default/2056/5/4/7.png

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin && docker push $DOCKER_ACCOUNT/$DOCKER_REPO
  on:
    branch: master
