version: '3.3'
services:
  sut:
    image: curlimages/curl:latest
    command: ["curl", "-f", "http://mapcache:8080/mapcache/wmts/1.0.0/WMTSCapabilities.xml"]
    depends_on:
      - mapcache
  mapcache:
    build: .
    image: ${IMAGE_NAME}
    ports:
      - "8080:8080"
