version: '3.3'
services:
  sut:
    image: curlimages/curl:latest
    command: ["curl", "-f", "http://mapcache:8080/wmts/1.0.0/WMTSCapabilities.xml"]
    depends_on:
      - mapcache
  mapcache:
    image: $DOCKER_NAMESPACE/$DOCKER_IMAGE:latest
    ports:
      - "8080:8080"
