services:
  wmts:
    image: sogis/mapcache:latest
    environment:
      DEMO_SERVICE_ENABLED: 'true'
    ports:
      - "8080:8080"
    volumes:
      - ${TILES_PATH}:/tiles
  wms:
    image: sourcepole/qwc-qgis-server:3.28.7
    environment:
      URL_PREFIX: /qgis
      FCGI_MIN_PROCESSES: 0
      FCGI_MAX_PROCESSES: 4
      FCGI_PROCESS_LIFE_TIME: 0
    ports:
      - "8081:80"
    volumes:
      - ./qgs:/data
      - ${GEODATA_PATH}:/geodata
