version: '3'
services:
  seeder:
    image: sogis/docker-mapcache:latest
    environment:
      ENVIRONMENT: 'seed'
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/mapcacheseed.xml:/mapcache/mapcacheseed.xml
      - ${TILES_PATH}:/tiles
    depends_on:
      - wms
  wms:
    image: sogis/qgis-server-base:3.10
    environment:
      QGIS_FCGI_MIN_PROCESSES: 4
      QGIS_FCGI_MAX_PROCESSES: 4
    ports:
      - "8081:80"
    volumes:
      - ${PWD}/qgs:/data
      - ${GEODATA_PATH:-./geodata}:/geodata
  pub-db:
    build: .
    image: sogis/postgis-db:localbuild
    environment:
      PG_DATABASE: pub
      PG_LOCALE: de_CH.UTF-8
      PG_PRIMARY_PORT: 5432
      PG_MODE: primary
      PG_USER: admin
      PG_PASSWORD: admin
      PG_PRIMARY_USER: repl
      PG_PRIMARY_PASSWORD: repl
      PG_ROOT_PASSWORD: secret
    ports:
      - "54322:5432"
    volumes:
      - ./setup.sql:/pgconf/setup.sql
      - sshd_pub:/sshd
      - pgconf_pub:/pgconf
      - pgdata_pub:/pgdata
      - pgwal_pub:/pgwal
      - recover_pub:/recover
      - backrestrepo_pub:/backrestrepo
    hostname: primary-pub
volumes:
  sshd_pub:
  pgconf_pub:
  pgdata_pub:
  pgwal_pub:
  recover_pub:
  backrestrepo_pub:
